[agent1]
  [agent1.host]
  key1 = "value1"
  key2 = "value2"

  [agent1.cpu]
  refresh_rate = "5"
  threshold = "80"

  [agent1.ram]
  monitor = "True"
  interval = "30"

  [agent1.disk_usage]
  excludes = ["^/snap/.+"]
  warning_level = "90"

  [agent1.ping]
  hosts = ["google.de", "familie-heise.de"]
