[defaults]
window_size = 10

[[rule]]
id = "cpu_high_single"
enabled = true
description = "CPU > 90% in einer einzelnen Messung"
pluginid = "cpu"
metric = "percent"
condition = "gt"
threshold = 10.0
scope = "single"
severity = "warning"

[[rule]]
id = "cpu_high_avg"
enabled = true
description = "CPU-Durchschnitt > 80% über letzte 20 Messungen"
pluginid = "cpu"
metric = "percent"
condition = "gt"
threshold = 80.0
scope = "moving_avg"
window_size = 20
severity = "critical"

[[rule]]
id = "ram_high_single"
enabled = true
description = "RAM > 90% in einer einzelnen Messung"
pluginid = "ram"
metric = "virtual_pct"
condition = "gt"
threshold = 90.0
scope = "single"
severity = "warning"
